// components/TheFooter.tsx
// components > TheFooter

import React from 'react'
import { css } from '@emotion/react'
import { AppContainer } from '@/components/AppGrid'

// Props
type Props = {}

// TheFooter
const TheFooter: React.FC<Props> = () => {
  const currentYear = () => {
    const date = new Date()
    return date.getFullYear()
  }

  // Styles
  const styledFooter = css`
    padding: 32px 0;
    font-family: 'sofia-pro', 'Hiragino Kaku Gothic ProN', 'Yu Gothic',
      sans-serif;
    font-size: 14px;
    text-align: center;
  `

  return (
    <AppContainer tag="footer">
      <div css={styledFooter}>
        <p>
          &copy; 2014-{currentYear()} {process.env.baseName}
        </p>
      </div>
    </AppContainer>
  )
}

export default TheFooter

// components/TheFooter.vue
<template>
  <app-container tag="footer" class="the-footer">
    <div class="the-footer__body">
      <p class="the-footer__copyright">
        &copy; 2014-{{ currentYear }} {{ $config.baseName }}
      </p>
    </div>
  </app-container>
</template>

<script>
export default {
  name: 'TheFooter',

  computed: {
    currentYear () {
      const date = new Date()
      return date.getFullYear()
    },
  },
}
</script>

<style lang="scss" scoped>
@use 'assets/sass/_' as *;
$root: '.the-footer';

.the-footer {
  background-color: transparent;
}

.the-footer__body {
  padding: 32px 40px;
}

.the-footer__copyright {
  font-family: $font-family-en;
  font-size: 14px;
  text-align: center;
}
</style>
