// components/TheHeader.tsx
// components > TheHeader

import React from 'react'
import Link from 'next/link'
import { css } from '@emotion/react'
import { AppButton } from '@/components/AppButton'
import { AppContainer } from '@/components/AppGrid'
import { AppIcon } from '@/components/AppIcon'
import { AppLogo } from '@/components/AppLogo'
import { breakpoints } from '@/utils/sizes'

// Props
type Props = {}

// TheHeader
const TheHeader: React.FC<Props> = () => {
  const onClick = (event: React.MouseEvent<HTMLButtonElement>): void => {
    console.log(event)
  }

  // Styles
  const styledHeader = css`
    display: flex;
    align-items: center;
    justify-content: space-between;
    height: 80px;
  `
  const styledHeaderLogo = css`
    display: inline-flex;
    width: 120px;
    color: inherit;
    opacity: 1;
    transition-property: opacity;
    &:hover {
      opacity: 0.6;
    }
    ${breakpoints('md')} {
      width: 168px;
    }
  `

  return (
    <AppContainer tag="header">
      <div css={styledHeader}>
        <Link href={process.env.baseDir || '/'} passHref>
          <a css={styledHeaderLogo} title={process.env.baseName}>
            <AppLogo />
          </a>
        </Link>
        <AppButton
          color="white"
          label="Color Mode"
          size="large"
          onClick={onClick}
          icon
        >
          <AppIcon size={20}>light_mode</AppIcon>
        </AppButton>
      </div>
    </AppContainer>
  )
}

export default TheHeader

// components/TheHeader.vue
<template>
  <app-container tag="header" class="the-header">
    <div class="the-header__body">
      <nuxt-link :title="$config.baseName" class="the-header__logo" to="/" exact>
        <app-logo />
      </nuxt-link>
      <app-button
        :color="dark ? 'gray-800' : 'white'"
        label="Color Mode"
        size="large"
        icon
        @click="toggleMode"
      >
        <span class="material-icons">
          {{ dark ? 'dark_mode' : 'light_mode' }}
        </span>
      </app-button>
    </div>
  </app-container>
</template>

<script>
export default {
  name: 'TheHeader',

  computed: {
    dark () {
      return this.$colorMode.value === 'dark'
    },
  },

  methods: {
    toggleMode () {
      this.$colorMode.preference = this.dark ? 'light' : 'dark'
    },
  },
}
</script>

<style lang="scss" scoped>
@use 'assets/sass/_' as *;
$root: '.the-header';

.the-header {
  background-color: transparent;
}

.the-header__body {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 80px;
}

.the-header__logo {
  display: inline-flex;
  width: 120px;
  opacity: 1;
  transition-property: color, background-color, opacity;

  &:hover {
    opacity: 0.6;
  }

  @include breakpoint(md) {
    width: 168px;
  }
}
</style>
