// src/pages/Index.vue
<template>
  <Layout>
    <div class="page">
      <div class="page__header">
        <img
          src="https://secure.gravatar.com/avatar/16f38857b5cc103612d1c3f2ff5df26e?s=136"
          alt="icon"
          class="page__icon"
          loading="lazy"
        >
      </div>
      <div class="page__body">
        <p class="page__name">{{ name }}</p>
        <p class="page__bio">{{ bio }}</p>
        <nav class="page__navigation">
          <ul class="page__navigation">
            <template v-for="item in navigation">
              <li :key="item.id">
                <g-link
                  :to="item.to"
                  :title="item.title"
                >
                  {{ item.label }}
                </g-link>
              </li>
            </template>
          </ul>
        </nav>
      </div>
    </div>
  </Layout>
</template>

<script>
export default {
  computed: {
    name() {
      return 'I am Hiratake.'
    },
    bio() {
      return '大阪でマークアップ園児とデザイナーやってます。'
    },
    navigation() {
      return [
        {
          id: 'blog',
          to: '/blog',
          label: 'Blog',
          title: 'ブログ',
        },
        {
          id: 'works',
          to: '/works',
          label: 'Works',
          title: '制作実績',
        },
        {
          id: 'contact',
          to: '/contact',
          label: 'Contact',
          title: '連絡先',
        },
      ]
    },
  },
}
</script>

<style>
.page {
  display: grid;
  grid-template-columns: 100%;
  grid-auto-rows: auto;
  gap: 32px;
  justify-items: center;
  max-width: 264px;
  text-align: center;
}

.page__body {
  display: grid;
  grid-template-columns: 100%;
  grid-auto-rows: auto;
  gap: 21px;
  justify-items: center;
}

.page__icon {
  display: block;
  border-radius: 50%;
}

.page__name {
  font-family: 'Sofia Pro', sans-serif;
  font-size: 40px;
  font-weight: 700;
}

.page__bio {
  font-size: 14px;
  color: var(--color-text-lighten);
}

.page__navigation ul {
  display: flex;
  list-style: none;
}

.page__navigation li ~ li {
  margin-left: 16px;
}

.page__navigation a {
  position: relative;
  display: block;
  padding: 4px 2px;
  font-family: 'Sofia Pro', sans-serif;
  font-size: 16px;
  font-weight: 700;
  color: inherit;
  text-decoration: none;
  transition-duration: var(--transition-duration);
}

.page__navigation a:hover {
  color: var(--color-text-lighten);
}

.page__navigation a::before,
.page__navigation a::after {
  position: absolute;
  right: 0;
  bottom: 0;
  width: 100%;
  height: 2px;
  content: '';
  background-color: var(--color-primary);
}

.page__navigation a::before {
  opacity: 0.32;
}

.page__navigation a::after {
  transition-duration: inherit;
}

.page__navigation a:hover::after {
  width: 4px;
}
</style>

// pages/index.tsx
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { css } from '@emotion/react'
import { AppTab } from '@/components'
import { breakpoints } from '@/utils/sizes'
import profile from '@/assets/profile.json'
import IconTwitter from '@/assets/images/twitter.svg'
import IconGitHub from '@/assets/images/github.svg'
import IconDiscord from '@/assets/images/discord.svg'
import { useState } from 'react'

const Home: NextPage = () => {
  // Styles
  const styledProfile = css`
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: center;
    padding: 56px 0;
    ${breakpoints('md')} {
      padding: 80px 0;
    }
  `
  const styledProfileIcon = css`
    width: 120px;
    height: 120px;
    overflow: hidden;
    border-radius: 50%;
  `
  const styledProfileContent = css`
    width: 100%;
    padding: 16px 40px 0 40px;
    font-family: 'sofia-pro', 'Hiragino Kaku Gothic ProN', 'Yu Gothic',
      sans-serif;
    text-align: center;
    ${breakpoints('md')} {
      max-width: 400px;
      padding-top: 0;
      padding-right: 0;
      text-align: left;
    }
  `
  const styledProfileName = css`
    font-size: 36px;
    font-weight: 700;
  `
  const styledProfileBio = css`
    max-width: 320px;
    margin: auto;
    font-size: 14px;
    color: var(--color-text-muted);

    ${breakpoints('sm')} {
      max-width: none;
    }
  `
  const styledProfileSocial = css`
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 16px;
    ${breakpoints('sm')} {
      justify-content: flex-start;
    }
  `
  const styledProfileSocialItem = css`
    display: flex;
    align-items: center;
    justify-content: center;
    width: 24px;
    height: 24px;
    padding: 2px;
    color: inherit;
    text-decoration: none;
    &:hover {
      color: var(--color-text-muted);
    }
    & ~ & {
      margin-left: 8px;
    }
  `
  const styledProfileSocialIcon = css`
    width: 100%;
    fill: currentColor;
  `
  const styledContent = css`
    padding: 24px 0 48px;
    ${breakpoints('md')} {
      padding: 40px 0 80px;
    }
  `

  const [currentTab, setCurrentTab] = useState('posts')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div css={styledProfile}>
        <div css={styledProfileIcon}>
          <Image src={profile.image} alt="Icon" width={120} height={120} />
        </div>
        <div css={styledProfileContent}>
          <p css={styledProfileName}>{profile.name}</p>
          <p css={styledProfileBio}>{profile.bio}</p>
          <div css={styledProfileSocial}>
            <Link href={profile.social.twitter} passHref>
              <a css={styledProfileSocialItem} target="_blank" rel="noopener">
                <IconTwitter css={styledProfileSocialIcon} />
              </a>
            </Link>
            <Link href={profile.social.github} passHref>
              <a css={styledProfileSocialItem} target="_blank" rel="noopener">
                <IconGitHub css={styledProfileSocialIcon} />
              </a>
            </Link>
            <Link href={profile.social.discord} passHref>
              <a css={styledProfileSocialItem} target="_blank" rel="noopener">
                <IconDiscord css={styledProfileSocialIcon} />
              </a>
            </Link>
          </div>
        </div>
      </div>

      <div css={styledContent}>
        <AppTab
          headers={[
            { label: 'posts', key: 'posts' },
            { label: 'works', key: 'works' },
          ]}
          current={currentTab}
          onChange={setCurrentTab}
        ></AppTab>
      </div>
    </>
  )
}

export default Home
